services:
  mysql:
    image: mysql:8.0
    container_name: campsite-db
    restart: always
    environment:
      - MYSQL_DATABASE=campsite
      - MYSQL_ROOT_PASSWORD=SomeRootPasswordToCampsite
      - MYSQL_USER=campsite
      - MYSQL_PASSWORD=SomePasswordToCampsite
    ports:
      - 3306:3306
    volumes:
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql


