server:
  port: ${PORT:8080}
  servlet:
    context-path: /campsite

spring:
  datasource:
    url: ${DB-URL:jdbc:mysql://localhost:3306/campsite?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DB-USER:campsite}
    password: ${DB-PASS:SomePasswordToCampsite}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

redis:
     host: ${REDIS-HOST:localhost}
     port: ${REDIS-PORT:9736}

campsite:
  max-advance-days: ${CAMPSITE_MAX_ADVANCE_DAYS:31}
  max-stay-days: ${CAMPSITE_MAX_STAY_DAYS:3}
  min-stay-days: ${CAMPSITE_MIN_STAY_DAYS:1}
  min-ahead-arrival-days: ${CAMPSITE_MIN_AHEAD_ARRIVAL_DAYS:1}
  max-ahead-arrival-days: ${CAMPSITE_MAX_AHEAD_ARRIVAL_DAYS:31}

cache:
  availabilityRangeDates:
    ttlMinutes: ${CACHE_AVAILABILITY_RANGE_DATES_TTL_MINUTES:60}

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

